[Community Translation] Russian docs translation updates
vuejs/vue-router pull request #1081
Opened 2017-01-08 08:03 UTC by gbezyuk

2017-01-08 13:36 UTC, simplesmiler requested changes

2017-01-08 13:36 UTC, simplesmiler commented on docs/ru/advanced/navigation-guards.md
> +Наконец, сторожевой хук можно указать и непосредственно в компоненте (того, что указан в конфигурации роутера), используя `beforeRouteEnter` и `beforeRouteLeave`:
Скорее всего имелось ввиду вот так:

... в компоненте (~~того~~ том, что указан в конфигурации ~~роутера~~ роута)...

2017-01-08 13:40 UTC, gbezyuk commented on docs/ru/advanced/navigation-guards.md
> +Наконец, сторожевой хук можно указать и непосредственно в компоненте (того, что указан в конфигурации роутера), используя `beforeRouteEnter` и `beforeRouteLeave`:
@Alex-Sokolov

2017-01-08 13:46 UTC, Alex-Sokolov commented on docs/ru/advanced/navigation-guards.md
> +Наконец, сторожевой хук можно указать и непосредственно в компоненте (того, что указан в конфигурации роутера), используя `beforeRouteEnter` и `beforeRouteLeave`:
Исправим, только вместо "роутов" везде решили использовать "пути"

2017-01-08 14:22 UTC, simplesmiler approved these changes

2017-01-08 14:29 UTC, simplesmiler commented
@Alex-Sokolov @gbezyuk а про капитализацию `Vue-router` вместо `vue-router` какой аргумент? Вроде  документация на остальных языках использует `vue-router`.

2017-01-08 14:34 UTC, Alex-Sokolov commented
@simplesmiler ну это же названия? Vue везде в документации с большой, Vuex (https://github.com/vuejs/vuex) тоже с большой (хотя местами его то с маленькой пишут, то с большой). Ну а Vue-router тоже получается должен быть с большой? Лучше же всё в едином стиле выдерживать

2017-01-08 14:39 UTC, simplesmiler commented
@Alex-Sokolov аргумент принимается, но наверное лучше это сделать отдельным PR, исправляющим капитализацию на всех языках, а не только на русском :wink:

2017-01-09 07:17 UTC, simplesmiler commented
If @gbezyuk has no futher changes in mind, then LGTM.
/cc @kazupon

2017-01-09 07:29 UTC, gbezyuk commented
I guess there will be some more updates, but in a separate PR later on.

2017-01-09 08:21 UTC, merged