Complete spanish translation
vuejs/vue-router pull request #1150
Opened 2017-02-09 20:53 UTC by zeratulmdq

2017-02-09 21:25 UTC, posva commented on docs/es/SUMMARY.md
> +  - [Coincidencia diámica de rutas](essentials/dynamic-matching.md)
dinámica

2017-02-09 21:43 UTC, posva commented
Hey, muchas gracias por la contribución, tardaré un tiempo en revisarlo todo, prefiero ir avisando 😄 

Veo que tratas de usted al usuario, se me hace muy raro leerlo en una doc, me siento como si estuviese leyendo el prospecto de un medicamento 😆 . He buscado un poco pero no logro encontrar otra documentación escrita en español y no sé si es común que esta esté escrita con usted. Opino que es mejor tutear al usuario pero no habituo leer docs en español y sé que es una cuestión de culturas, así que, si tienes algunas referencias por ahí me encantaría echarle un ojo

2017-02-09 21:55 UTC, zeratulmdq commented
De nada! Espectacular que lo revises, se me complica hablar en neutro siendo argentino, hay cosas que sinceramente no se como traducir y que me entiendan todos.

No leo documentación es español, pero según las reglas de GNU se debe tratar al usuario de usted. La verdad es que no me gusta tampoco, pero como empecé con la traducción de Vue y ellos pusieron esa regla, pensé que era algo deseable. Si te parece que lo cambie y tutee al usuario para mi es incluso mejor. 

Para el fin de semana termino con la doc de Vuex también.

2017-02-09 22:12 UTC, posva commented
Si tú tambiém lo ves mejor así, yo creo que merece la pena. Ya sabemos que GNU tienen reglas algo anticuadas y son a veces demasiado strictos 😆

2017-02-10 20:05 UTC, zeratulmdq commented
Ya está todo pasado de _usted_ a _tú_ junto con algunas correciones menores.

2017-02-12 04:33 UTC, PierBover commented
Llego tarde a la fiesta pero creo que @zeratulmdq está usando muchos términos locales que no se entienden en otros países de habla hispana o simplemente no son suficientemente neutros.

Por ejemplo en España "tope de la página" sonaría raro como si dijeras "techo de la página", y en México lo más probable es que no se entienda. Me he encontrado con estas situaciones muchas veces ya que soy español pero llevo 8 años viviendo en México. Mi mujer es traductora para español latinoamericano y se pelea con esto todos los días.

Por otro lado creo que sería buena idea mantener algunos términos técnicos como `router` en inglés ya que palabras como "ruteo", "enrutador", etc, no existen en español.

Finalmente hay palabras que a pesar de que existen en español, son "false friends" y no se pueden traducir directamente. Un ejemplo es "programático". En español esto no tiene que ver con un programa informático, si no con un programa electoral o un plan de cosas que se van a hacer.

http://dle.rae.es/?id=UJYoaj2

Si me lo permiten me gustaría pulir las traducciones de @zeratulmdq antes de que @posva acepte el PR.

2017-02-12 11:36 UTC, posva commented
@PierBover Me alegro de poder contar con tu ayuda. Solo he leído unos párrafos. Se me hace raro leer ciertos términos como ruteo pero la verdad es que tengo muy poca experiencia usando documentación en español. Siempre la leo en inglés y a pesar de ser español, estudié en Francia así que no he usado a penas términos españoles en informática.

> Por otro lado creo que sería buena idea mantener algunos términos técnicos como router en inglés ya que palabras como "ruteo", "enrutador", etc, no existen en español.

👍 

Si @zeratulmdq te puede dar acceso a su fork para que puedas contribuir directamente, yo podré centrarme en que la documentación sea fiel a la original desde un punto técnico.

Me parece genial que tengas un entorno Méxicano para que la traducción sea accesible a toda persona de Habla hispana 🙂

2017-02-12 11:49 UTC, zeratulmdq commented
@PierBover puede asegurarte que los términos del estilo _tope_ los traté de utilizar pensando en neutro. Incluso ese término en particular lo consulte con otras personas de otros países. Te diría que no utilice ninguna palabra "argentina".

Entiendo que muchos términos no tienen traducción directa o son falsos amigos, pero tampoco se puede dejar la traducción entera llena de anglicismos porque quien lee la documentación en español es alguien que normalmente no entiende inglés. Cosas como _router, spa, frontend, backend, runtime, hook, calback, handler, programmatically, bundler_ y un sin fin mas **nunca** las digo en español, pero cuando pude busqué la manera que consideré correcta de ponerlas en español.

2017-02-12 11:57 UTC, posva commented
> Entiendo que muchos términos no tienen traducción directa o son falsos amigos, pero tampoco se puede dejar la traducción entera llena de anglicismos porque quien lee la documentación en español es alguien que normalmente no entiende inglés. Cosas como router, spa, frontend, backend, runtime, hook, calback, handler, programmatically, bundler y un sin fin mas nunca las digo en español, pero cuando pude busqué la manera que consideré correcta de ponerlas en español.

Seguro que se puede encontrar un término medio 🙂

2017-02-12 16:43 UTC, PierBover commented
> por supuesto que no tengo problema en agregarte a la organización y discutimos término por término la manera correcta de hacerlo

Perfecto @zeratulmdq pues seguimos por ahí.

#  👍

2017-02-12 16:45 UTC, PierBover commented
> Siempre la leo en inglés y a pesar de ser español, estudié en Francia así que no he usado a penas términos españoles en informática.

Yo estudié en el lycée français y viví en un país francófono durante años. 😄

2017-02-16 14:18 UTC, posva commented
@zeratulmdq @PierBover Decidme cuando haya partes que puedo revisar 🙂

2017-02-16 14:32 UTC, PierBover commented
Hola @posva 

Aquí puedes ver las pautas de traducción que hemos ido acordando:
https://github.com/es-vuejs/vuejs.org/issues/1

Aquí puedes ver el avance de vuejs.org:
https://es-vuejs.github.io/vuejs.org/
https://github.com/es-vuejs/vuejs.org

Este es el branch para vue-router:
https://github.com/es-vuejs/vue-router/tree/pr/spanish-translation

Este es el branch para vuex:
https://github.com/es-vuejs/vuex/tree/pr/spanish-translation

Es prácticamente todo trabajo de @zeratulmdq

2017-02-25 14:09 UTC, aferrop commented
Gracias por el gran avance que han hecho en las traducciones, me apunto a realizar revisiones

2017-02-25 16:05 UTC, PierBover commented
@aferrop aqui puedes ver como vamos con la web de Vue y las cosas que están en curso.

https://github.com/es-vuejs/vuejs.org/issues/3

2017-04-06 05:49 UTC, yyx990803 commented
@posva feel free to merge this one when you feel it's ready.

2017-04-06 12:49 UTC, posva commented
hey @zeratulmdq @PierBover Finalmente, reviso esta traducción o no? Hay aún muchos términos que pienso es mejor guardar en ingles, por eso me preguntaba si ya habíais pasado por encima o teníais otras prioridades

2017-04-06 14:42 UTC, zeratulmdq commented
@posva estoy trabajando sobre la traducción principal de Vue, pero ahora dependo de que otras personas revisen lo que hice. Viendo que lo otro no avanza tan rápido, déjame revisar esto nuevamente a mi antes que lo hagas tú. En un día lo reviso y te aviso.

2017-04-06 15:22 UTC, DanielPe05 commented
Voy a echarle un vistazo también si no les molesta. Lo mire todo por encima y me pareció que hay ciertas cosas que son parte del propio vue-router que me parece que es mejor dejar en ingles. Voy a tratar de leerlo todo con calma esta noche y hacer sugerencias.

2017-04-06 19:29 UTC, zeratulmdq commented
@posva @DanielPe05 ya revisé la documentación completa. Modifiqué algunos términos que me marcaron anteriormente, por ejemplo:

* Enrutador -> quedó en inglés (router)
* Simple -> sencillo
* Array -> vector en lugar de arreglo
* Programáticamente -> mediante código
* Scroll -> usaba desplazamiento pero lo dejé en inglés
* Tope -> inicio
* Guardias -> lo utilizaba como sustantivo masculino pero me dijeron que lo ponga femenino porque se entendía mejor.

Seguí todos los lineamientos de la traducción principal de Vue, [pueden verse aquí](https://github.com/es-vuejs/vuejs.org/issues/1)

2017-04-07 14:35 UTC, DanielPe05 reviewed
He revisado todo, y hay pequeñas cosas que considero deben ser cambiadas, especialmente lo de `anidadas`, pero sobre todo creo que esta muy bien. Aun tengo duda en el uso de `vector` en lugar de `array`, se siente estraño. Pero no lo mencione porque creo que se había sugerido lo contrario.

2017-04-07 14:35 UTC, DanielPe05 commented on docs/es/advanced/data-fetching.md
> +- **Obtener la información después de la navegación**: realiza la navegación primero y luego obtén los datos en un _hook_ del ciclo de vida del componente entrante. Muestra algún tipo de indicador de
> Muestra algún tipo de indicador de carga mientras esperas la llegada de la información.

Creo que es mejor si dices algo como esto: 
> Mientras esperas la respuesta del servidor, este _hook_ puede ser usado para mostrar un indicador de carga.

2017-04-07 14:35 UTC, DanielPe05 commented on docs/es/advanced/data-fetching.md
> +Cuando utilizamos este enfoque, navegamos y renderizamos el componente entrante inmediatamente, y obtenemos los datos en el _hook_ `create` del componente. Nos posibilita mostrar un indicador de esta
> Nos posibilita mostrar un indicador de estado de carga mientras se obtiene la información a través de la red, y también podemos manejar la carga de datos de manera diferente para cada vista.

> Nos posibilita mostrar un indicador de estado de carga mientras se obtiene la información desde un servidor remoto, y también podemos manejar la carga de datos de manera diferente para cada vista.

2017-04-07 14:35 UTC, DanielPe05 commented on docs/es/advanced/lazy-loading.md
> +Cuando se construyen aplicaciones con un sistema de empaquetamiento de módulos, el archivo JavaScript resultante puede terminar siendo muy grande, afectando los tiempos de carga de la página. Sería m
> Cuando se construyen aplicaciones con un sistema de empaquetamiento de módulos

Yo usaria:
>Cuando se construyen aplicaciones con un sistema de agrupar módulos

2017-04-07 14:35 UTC, DanielPe05 commented on docs/es/advanced/meta.md
> +    // esta ruta requiere autentiación, verificamos que haya iniciado sesión
> autentiación 

es:
> autenticación

2017-04-07 14:35 UTC, DanielPe05 commented on docs/es/advanced/navigation-guards.md
> +Las guardias _before_ globales son llamados por orden de creación, cuando una navegación es disparada. Las guardias pueden ejecutarse asincrónicamente, y la navegación se considera **pendiente** hast
> Las guardias _before_ globales son llamados por orden de creación, cuando una navegación es disparada.

creo que seria mejor:
> Las guardias _before_ globales son llamadas por orden de creación, cuando una navegación comienza.

Nota _llamadas_ en femenino.

2017-04-07 14:35 UTC, DanielPe05 commented on docs/es/essentials/getting-started.md
> +// 0. Si utilizas un sistema de empaquetamiento de módulos (por ejemplo, a través de vue-cli), importa Vue y VueRouter y luego ejecuta Vue.use(VueRouter).
Otra vez, me gusta mas como suena:
> Un sistema de agrupar módulos

2017-04-07 14:35 UTC, DanielPe05 commented on docs/es/installation.md
> +Cuando lo utilices con un sistema de empaquetamiento de módulos, debes instalarlo explícitamente a través de `Vue.use()`:
> sistema de agrupar módulos

2017-04-07 14:35 UTC, DanielPe05 commented on docs/es/SUMMARY.md
> +  - [Rutas anidadas](essentials/nested-routes.md)
Anidadas es la traducción literal de `nested` pero creo que el contexto es completamente diferente. He estado rompiéndome la cabeza, pensando a ver como podemos llamar eso, sin embargo no se me ocurre nada, pero si se, que en este contexto anidado no es lo mismo que nested. Se refiere mas como a `Sub-routes`. Creo que debemos pensar en esto un poco mas, se usa en varias partes.

2017-04-07 14:47 UTC, zeratulmdq commented on docs/es/advanced/data-fetching.md
> +- **Obtener la información después de la navegación**: realiza la navegación primero y luego obtén los datos en un _hook_ del ciclo de vida del componente entrante. Muestra algún tipo de indicador de
Me parece bien.

2017-04-07 14:47 UTC, zeratulmdq commented on docs/es/advanced/data-fetching.md
> +Cuando utilizamos este enfoque, navegamos y renderizamos el componente entrante inmediatamente, y obtenemos los datos en el _hook_ `create` del componente. Nos posibilita mostrar un indicador de esta
Me parece bien.

2017-04-07 14:48 UTC, zeratulmdq commented on docs/es/advanced/meta.md
> +    // esta ruta requiere autentiación, verificamos que haya iniciado sesión
Corregir.

2017-04-07 14:49 UTC, zeratulmdq commented on docs/es/advanced/lazy-loading.md
> +Cuando se construyen aplicaciones con un sistema de empaquetamiento de módulos, el archivo JavaScript resultante puede terminar siendo muy grande, afectando los tiempos de carga de la página. Sería m
Empaquetamiento de módulos fue una decisión tomada en base a diferentes formas de llamar las cosas en Argentina, México y España luego de debatirlo con @PierBover . @posva que opinas? Creo que queda mejor como lo puse yo, pero si la forma de @DanielPe05 te parece mejor lo modifico en toda la documentación.

2017-04-07 14:49 UTC, zeratulmdq commented on docs/es/advanced/navigation-guards.md
> +Las guardias _before_ globales son llamados por orden de creación, cuando una navegación es disparada. Las guardias pueden ejecutarse asincrónicamente, y la navegación se considera **pendiente** hast
Me parece bien.

2017-04-07 14:51 UTC, zeratulmdq commented
El tema de vector es complicado. En Argentina le decimos arreglo. Me pidieron que lo ponga como vector (lo cual también me parece raro) o que lo deje como _array_, pero siento que es una palabra que no vale la pena dejar en inglés. Escucho sugerencias si no les parece correcto.

2017-04-07 14:52 UTC, zeratulmdq commented on docs/es/SUMMARY.md
> +  - [Rutas anidadas](essentials/nested-routes.md)
Podemos decirle sub-rutas o rutas hijas?

2017-04-07 15:12 UTC, PierBover commented
Hola a todos. Estuve desaparecido en modo crunch con el trabajo.

En cuanto a _array_ [la RAE lo mantiene en inglés](http://diccionario.raing.es/es/lema/array-0) y lo define como una _matriz_.

Yo opino que si nos vamos a dirigiar a toda la comunidad hispana habría que seguir algo oficial. Si no nos vamos a perder discutiendo como le dice cada quién en su país.

2017-04-07 15:16 UTC, PierBover commented on docs/es/SUMMARY.md
> +  - [Rutas anidadas](essentials/nested-routes.md)
@DanielPe05 `nested` y `sub-routes` es lo mismo. De hecho en versiones anteriores del router la propiedad que ahora se llama `children` antes se llamaba `subRoutes`.

@zeratulmdq a mi _sub-rutas_ me suena bien.

2017-04-07 15:19 UTC, PierBover commented on docs/es/essentials/getting-started.md
> +// 0. Si utilizas un sistema de empaquetamiento de módulos (por ejemplo, a través de vue-cli), importa Vue y VueRouter y luego ejecuta Vue.use(VueRouter).
@DanielPe05 pero "agrupar módulos" es incorrecto ya que esto se refiere a sistemas como `webpack`, `rollup`, etc, que hacen mucho más que simplemente agrupar.

2017-04-07 15:20 UTC, PierBover commented on docs/es/advanced/lazy-loading.md
> +Cuando se construyen aplicaciones con un sistema de empaquetamiento de módulos, el archivo JavaScript resultante puede terminar siendo muy grande, afectando los tiempos de carga de la página. Sería m
Agrupar no es lo mismo que empaquetar. Sistemas como `webpack` o `rollup` hacen mucho más que agrupar módulos.

2017-04-07 15:31 UTC, DanielPe05 commented on docs/es/SUMMARY.md
> +  - [Rutas anidadas](essentials/nested-routes.md)
Estoy de acuerdo con `sub-rutas`, es la palabra `anidadas` la que esta fuera de contexto completamente.

2017-04-07 15:33 UTC, DanielPe05 commented on docs/es/advanced/lazy-loading.md
> +Cuando se construyen aplicaciones con un sistema de empaquetamiento de módulos, el archivo JavaScript resultante puede terminar siendo muy grande, afectando los tiempos de carga de la página. Sería m
Tienes, razón. Webpack hace mucho mas que solo agrupar, estaba tratando de encontrar algo mas corto y fácil de recordar que empaquetamiento. Pero estoy de acuerdo que agrupar no es el termino correcto.

2017-04-07 15:35 UTC, DanielPe05 commented
Estoy de acuerdo con @PierBover, creo que deberíamos dejarlo como `array` o `matrix` me suena bien.

2017-04-07 22:07 UTC, zeratulmdq commented
Listo @posva 

Quedó _array_ en lugar de arreglo y _sub-ruta_ en lugar de rutas anidadas. El resto de los lugares donde se utilizaba la palabra anidada lo dejé así.

2017-04-12 10:41 UTC, posva requested changes

2017-04-12 10:41 UTC, posva commented on docs/es/SUMMARY.md
> +  - [Carga diferida](advanced/lazy-loading.md)
Esto mejor dejarlo en ingles, no?

2017-04-12 10:41 UTC, posva commented on docs/es/SUMMARY.md
> +  - [Coincidencia dinámica de rutas](essentials/dynamic-matching.md)
Pienso que es mejor guardar Matching

2017-04-12 10:41 UTC, posva commented on docs/es/SUMMARY.md
> +  - [Inyección de componentes](api/component-injections.md)
es inyección **en** componentes

2017-04-12 10:41 UTC, posva commented on docs/es/advanced/data-fetching.md
> +Puede que necesites obtener datos desde el servidor cuando una ruta es activada. Por ejemplo, antes de renderizar un perfil de usuario, puedes obtener la información de ese usuario desde el servidor.
A veces es necesario obtener datos del servidor cuando...

por que desde en vez de del?

2017-04-12 10:41 UTC, posva commented on docs/es/advanced/data-fetching.md
> +- **Obtener la información después de la navegación**: realiza la navegación primero y luego obtén los datos en un _hook_ del ciclo de vida del componente entrante. Mientras esperas la respuesta del
> Mientras esperas la respuesta del servidor, este _hook_ puede ser usado para mostrar un indicador de carga.

Puedes mostrar un indicador de carga mientras se obtienen los datos.

2017-04-12 10:41 UTC, posva commented on docs/es/advanced/data-fetching.md
> +- **Obtener la información antes de la navegación**: Obtén los datos antes de la navegación en la guardia de entrada de la ruta, y realiza la navegación luego de haberla obtenido.
> luego de haberla obtenido
una vez estos obtenidos

2017-04-12 10:41 UTC, posva commented on docs/es/advanced/data-fetching.md
> +Técnicamente, ambas opciones son válidas - depende de la experiencia de usuario a la que apuntes.
**todo** depende de la experiencia que quieras porporcionar al usuario

2017-04-12 10:41 UTC, posva commented on docs/es/advanced/data-fetching.md
> +Cuando utilizamos este enfoque, navegamos y renderizamos el componente entrante inmediatamente, y obtenemos los datos en el _hook_ `create` del componente. Nos posibilita mostrar un indicador de esta
created

nos posibilita --> Esto nos permite
~podemos~ manejar .. ~de manera diferente para cada~ según la vista
Me pregunto si decir _ruta_ en vez de vista queda más claro, creo que sí

2017-04-12 10:41 UTC, posva commented on docs/es/advanced/data-fetching.md
> +Cuando utilizamos este enfoque, navegamos y renderizamos el componente entrante inmediatamente, y obtenemos los datos en el _hook_ `create` del componente. Nos posibilita mostrar un indicador de esta
si, mejor usar ruta

2017-04-12 10:41 UTC, posva commented on docs/es/advanced/data-fetching.md
> +El usuario permanecerá en la vista actual mientras se esté obteniendo el recurso para la vista entrante. Por lo tanto, es recomendable mostrar algún tipo de indicador o barra de progreso. Si la obten
tipo de advertencia global

2017-04-12 10:41 UTC, posva commented on docs/es/advanced/lazy-loading.md
> +Cuando se construyen aplicaciones con un sistema de empaquetamiento de módulos, el archivo JavaScript resultante puede terminar siendo muy grande, afectando los tiempos de carga de la página. Sería m
Yo prefiero guardar los términos que habéis elegido. Me fijo más en que lo que se dice sea correcto para vue-router y vue y algunás que otras frases que suenan raras

2017-04-13 19:23 UTC, zeratulmdq commented on docs/es/SUMMARY.md
> +  - [Coincidencia dinámica de rutas](essentials/dynamic-matching.md)
¿Te parece que suena mejor "Matching de rutas dinámico" o "Matcheo dinámico de rutas"?

2017-04-13 19:26 UTC, zeratulmdq commented on docs/es/advanced/data-fetching.md
> +Puede que necesites obtener datos desde el servidor cuando una ruta es activada. Por ejemplo, antes de renderizar un perfil de usuario, puedes obtener la información de ese usuario desde el servidor.
Se usan indistintamente en Argentina, pero si queda más claro usando _del_ en lugar de _desde_, lo cambio.

2017-04-19 14:17 UTC, posva commented on docs/es/SUMMARY.md
> +  - [Coincidencia dinámica de rutas](essentials/dynamic-matching.md)
Matching dinamico de rutas me parece bien

2017-04-19 15:06 UTC, zeratulmdq commented
@posva listos los cambios. En el archivo meta.md se conjuga el verbo _to match_ y me pareció mejor dejarlo en español, porque no incluye la palabra ruta y se entiende el contenido. Cualquier cosa me avisas.

2017-05-12 15:41 UTC, posva requested changes
Muy buen trabajo. Se ve bien trabajada la traducción 🙂 💯

2017-05-12 15:41 UTC, posva commented on docs/es/advanced/navigation-guards.md
> +Como el nombre sugiere, las guardias de navegación provistas por `vue-router` son básicamente utilizadas para proteger rutas de navegación ya sea redireccionando o cancelandolas. Hay varias maneras d
cancelándolas

2017-05-12 15:41 UTC, posva commented on docs/es/advanced/navigation-guards.md
> +Las guardias _before_ globales son llamadas por orden de creación, cuando una navegación comienza. Las guardias pueden ejecutarse asincrónicamente, y la navegación se considera **pendiente** hasta ta
hasta ~~tanto~~ que

2017-05-12 15:41 UTC, posva commented on docs/es/advanced/navigation-guards.md
> +**Asegúrese de llamar siempre a la función `next`, de otra manera el _hook_ nunca será resuelto.**
de otra manera -> sino

2017-05-12 15:41 UTC, posva commented on docs/es/advanced/scroll-behavior.md
> +Cuando se utiliza enrutamiento del lado cliente, podemos querer hacer `scroll` hacia el inicio de la página cuando naveguemos a una nueva ruta, o preservar la posición actual, tal cual lo hace una re
navegacíon

2017-05-12 15:41 UTC, posva commented on docs/es/advanced/scroll-behavior.md
> +La función `scrollBehavior` recibe los objetos de ruta `to` y `from`. El tercer parámetro, `savedPosition`, solo está disponible si estamos en una navegación `popstate` (cuando se utilizan los botone
atrás

2017-05-12 15:41 UTC, posva commented on docs/es/advanced/scroll-behavior.md
> +Devolver `savedPosition` hará que el comportamiento cuando se utilicen los botones _atras_ o _adelante_ sea el nativo:
atràs

2017-05-12 15:41 UTC, posva commented on docs/es/api/router-link.md
> +  Especifica el evento(s) que será(n) disparado(s) cuando se acceda al enlace.
son los eventos que permiten lanzar la navegacion

2017-05-12 15:41 UTC, posva commented on docs/es/essentials/dynamic-matching.md
> +
Puedes añadir la actualizacionde la 2.2 ?

Or, use the beforeRouteUpdate guard introduced in 2.2:

```js
const User = {
  template: '...',
  beforeRouteUpdate (to, from, next) {
    // react to route changes...
    // don't forget to call next()
  }
}
```
(http://router.vuejs.org/en/essentials/dynamic-matching.html)

2017-05-12 15:41 UTC, posva commented on docs/es/essentials/getting-started.md
> +> Todos los ejemplos utilizarán la versión independiente de Vue para hacer posible el análisis de plantillas. Más detalles [aquí](http://vuejs.org/guide/installation.html#Standalone-vs-Runtime-only-B
el linke cambio: https://vuejs.org/v2/guide/installation.html#Runtime-Compiler-vs-Runtime-only

2017-05-12 15:41 UTC, posva commented on docs/es/essentials/navigation.md
> +Además de utilizar `<router-link>` para crear etiquetas _a_ para una navegación declarativa, podemos hacer lo mismo a través de código usando los métodos de la instancia del enrutador.
etiquetas `a`

2017-05-13 18:25 UTC, zeratulmdq commented
@posva listo los cambios, ya casi estamos. Habia freezado la versión a traducir para no meter más cosas, pero agregué igualmente lo que me pediste de la versión 2.2. Mi idea era una vez terminado esto, empezar con los cambios y agregados que se fueron haciendo a la documentación desde que yo empecé a traducir.

2017-05-17 09:31 UTC, posva approved these changes

2017-05-17 09:36 UTC, merged