[Just Merge Me] Russian Translation Update (history cleared)
vuejs/vue-router pull request #1368
Opened 2017-04-24 14:37 UTC by gbezyuk

2017-04-24 14:37 UTC, gbezyuk commented
ping @posva

2017-04-24 14:48 UTC, simplesmiler requested changes

2017-04-24 14:48 UTC, simplesmiler commented on docs/ru/api/router-instance.md
> +  С версии 2.5.0+ все три методы возвращают функцию, которая удаляет зарегистрированный хук.
`все три методы` -> `все три метода`

2017-04-24 14:48 UTC, simplesmiler commented on docs/ru/api/router-link.md
> +  Укажите активный CSS-класс, применяемый когда ссылка активна с точным соответствием маршрута. Обратите внимание, что значение по умолчанию также может быть настроено глобально с помощью опции `link
Может лучше `в  конструкторе VueRouter`?

2017-04-24 15:19 UTC, gbezyuk commented
ping @Alex-Sokolov

2017-04-25 02:34 UTC, gbezyuk commented
Ping @simplesmiler

2017-04-25 07:41 UTC, simplesmiler approved these changes

2017-04-25 09:22 UTC, merged