[Korean] Update vue-router 2.5
vuejs/vue-router pull request #1370
Opened 2017-04-25 12:42 UTC by ChangJoo-Park

2017-04-26 11:43 UTC, kazupon requested changes
Thank you for your PR!
Please check my review comment 💬

2017-04-26 11:43 UTC, kazupon commented on docs/kr/advanced/navigation-guards.md
> +In 2.5.0+ you can register a global guard with `router.onResolve`. This is similar to `router.beforeEach`, with the difference that resolve guards will be called right before the navigation is confir
Did you forget to remove it?

2017-04-26 13:07 UTC, ChangJoo-Park commented on docs/kr/advanced/navigation-guards.md
> +In 2.5.0+ you can register a global guard with `router.onResolve`. This is similar to `router.beforeEach`, with the difference that resolve guards will be called right before the navigation is confir
Oh, It is my mistake 😭

2017-04-26 13:15 UTC, ChangJoo-Park commented
Sorry @kazupon :sob: I forgot to remove original sentences

2017-04-26 14:57 UTC, kazupon approved these changes

2017-04-26 14:57 UTC, merged

2017-04-26 14:57 UTC, kazupon commented
Thanks!

2017-04-27 00:01 UTC, ChangJoo-Park commented
:)