Prevent unnecessary Exception with non-existent links
vuejs/vue-router pull request #1387
Opened 2017-04-30 17:58 UTC by posva

Closes #1386

2017-05-01 01:35 UTC, kazupon approved these changes

2017-05-01 06:35 UTC, yyx990803 requested changes

2017-05-01 06:35 UTC, yyx990803 commented on src/create-matcher.js
> +      if (process.env.NODE_ENV !== 'production' && !record) {
behavior should be consistent between prod and dev, so we should move the env check to only apply to the warning.

2017-05-17 13:31 UTC, posva commented
I forgot to ping you @yyx990803 😓

2017-06-16 04:33 UTC, merged