[Doc 🇫🇷] — All files — French Translation Done
vuejs/vue-router pull request #1608
Opened 2017-07-17 06:28 UTC by Haeresis

We are the [Vue-FR](https://github.com/vuejs/vuejs.org#french) team. We provide our translation on Vue Router part (with cross consistency from others Vue documentations).

Translated files:
- All!

Process:
- We will track all futur modifications from `en` directory because in our `working` branch we use the `en` directory to work. All futur `en` modifications at an already translated position will warns us with a conflict.
- We reverse all work done from `:working/en` to `:dev/fr` and we will provide some pull request each time a (set of) page(s) will be translated/updated.

2017-07-17 06:52 UTC, Haeresis commented
Why CircleCl failed? We have only add `.md` files to `fr`

2017-08-01 15:44 UTC, Haeresis commented
Hi @posva. What can I do to allows this PR to be accepted?

2017-08-14 07:42 UTC, Haeresis commented
Hi @posva !

Bump ! ;)

2017-08-15 16:04 UTC, posva commented
I'll give it a look as soon as I can

2017-08-24 07:20 UTC, Haeresis commented
Hi @posva 

I translated the new navigation.md part in french.

All files are ready for merge.

2017-08-24 07:28 UTC, Haeresis commented
I have also change two minor consistency things in EN doc.

An unecessary return line and a `2.2` that's become `2.2+`

2017-08-27 15:35 UTC, posva requested changes

2017-08-27 15:35 UTC, posva commented on docs/fr/advanced/navigation-guards.md
> +    // accèr à l'instance du composant via `vm`
accès

2017-08-27 15:35 UTC, posva commented on docs/fr/essentials/navigation.md
> +**Note:** If the destination is the same as the current route and only params are changing (eg: going from one profile to another `/users/1` -> `/users/2`), you will have to use [beforeRouteUpdate](.
Elle s'est échapé, cette note 😄

2017-08-28 07:03 UTC, Haeresis commented
Merci @posva !

2017-08-28 07:03 UTC, Haeresis commented on docs/fr/essentials/navigation.md
> +**Note:** If the destination is the same as the current route and only params are changing (eg: going from one profile to another `/users/1` -> `/users/2`), you will have to use [beforeRouteUpdate](.
Je l'ai rattrapée !

2017-08-28 08:52 UTC, posva approved these changes
Merci!

2017-08-28 08:55 UTC, merged

2017-08-28 08:59 UTC, Haeresis commented
Super ! 🎆

2017-09-05 08:46 UTC, Haeresis commented
Hi @posva !

What is the frequency of update for https://router.vuejs.org/fr/?

I'm currently waiting to propose French translation to French public via social networks etc. because currently there is still the previous content (half English / half French).

I can do something?

2017-09-05 15:57 UTC, posva commented
I deployed it!