Make scrollBehavior work with transitions by handling a promise (fixes #1263)
vuejs/vue-router pull request #1758
Opened 2017-09-25 11:51 UTC by homerjam

2017-09-25 12:03 UTC, homerjam commented
Not sure why tests are working locally but not on CI, anyone?

2017-09-25 12:15 UTC, blake-newman requested changes
@homerjam just rerun the tests to ensure it was not something CI end. Looks like it is a consistent failure. Could be something to do with the test implementation. 

Could you try something more specific that just a setTimeout. Perhaps use the transition API to hook into when the animation is complete. https://vuejs.org/v2/guide/transitions.html#JavaScript-Hooks

There are events you can hook into, that should give you the desired affect. https://vuejs.org/v2/api/#transition

2017-09-25 14:37 UTC, homerjam commented
Hi @blake-newman tracked down the test issue to me using async/await which didn't work in phantomjs.

Re. the transition API - that was one of my initial thoughts, however by my understanding we're unable to use it programatically from the `scrollBehavior` hook. However I think the user could maybe use it to emit an event which the `scrollBehavior` hook then listens for (I'm pretty new to Vue so assuming it's possible to emit/listen to events on the root/app).

2017-09-27 15:23 UTC, homerjam commented
Hey @pi0 any thoughts on this re. how it tackles https://github.com/nuxt/nuxt.js/issues/1376?

2017-10-11 19:53 UTC, yyx990803 commented
Although this does not automatically solve the transition problem, it does expose a useful async primitive for users to tackle this problem in userland.

2017-10-11 19:54 UTC, merged

2017-10-12 14:21 UTC, iamdubx commented
Will it be documented, how to use this primitive?

2017-10-12 14:22 UTC, yyx990803 commented
See https://router.vuejs.org/en/advanced/scroll-behavior.html at bottom