[doc][zh-cn] keep updates
vuejs/vue-router pull request #1774
Opened 2017-09-29 10:23 UTC by Jinjiang

/ping @Justineo

2017-10-02 16:49 UTC, Justineo requested changes

2017-10-02 16:49 UTC, Justineo commented on docs/zh-cn/SUMMARY.md
> +> 注意: vue-router@2.x 只适用于 Vue 2.x。0.7.x 版本的文档在[这里](https://github.com/vuejs/vue-router/tree/1.0/docs/zh-cn)。
问一下，为啥 0.7.x 的版本在 1.0 分支呀……

2017-10-02 16:49 UTC, Justineo commented on docs/zh-cn/advanced/data-fetching.md
> +- **导航完成之前获取**：导航完成前，在路由进入的拦截中获取数据，在数据获取成功后执行导航。
拦截 &rarr; 守卫

2017-10-02 16:49 UTC, Justineo commented on docs/zh-cn/advanced/lazy-loading.md
> +结合 Vue 的[异步组件](https://cn.vuejs.org/guide/components.html#异步组件)和 Webpack 的 [code splitting feature](https://doc.webpack-china.org/guides/code-splitting-async/#require-ensure-/), 轻松实现路由组件的懒加载。
代码分割功能？

2017-10-02 16:49 UTC, Justineo commented on docs/zh-cn/advanced/lazy-loading.md
> +首先，可以将异步组件定义为返回一个 Promise 的工厂函数 (该函数返回的Promise应该 resolve 组件本身):
Promise 空格

2017-10-02 16:49 UTC, Justineo commented on docs/zh-cn/advanced/lazy-loading.md
> +第二，在 webpack 2 中,我们可以使用[动态 import](https://github.com/tc39/proposal-dynamic-import)语法来定义代码分块点 (split point):
`webpack 2 中,` &rarr; `Webpack 2 中，`

2017-10-02 16:49 UTC, Justineo commented on docs/zh-cn/advanced/lazy-loading.md
>  import('./Foo.vue') // returns a Promise
返回 Promise

2017-10-02 16:49 UTC, Justineo commented on docs/zh-cn/advanced/lazy-loading.md
> +>注意:如果您使用的是 babel,你将需要添加[syntax-dynamic-import](https://babeljs.io/docs/plugins/syntax-dynamic-import/)插件,才能使 babel 可以正确地解析语法
* 全角标点
* babel &rarr; Babel

2017-10-02 16:49 UTC, Justineo commented on docs/zh-cn/advanced/lazy-loading.md
>  结合这两者，这就是如何定义一个能够被 webpack自动代码分割的异步组件
大小写和空格

2017-10-02 16:49 UTC, Justineo commented on docs/zh-cn/advanced/lazy-loading.md
>  有时候我们想把某个路由下的所有组件都打包在同个异步块(chunk)中。只需要使用 [命名 chunk](https://webpack.js.org/guides/code-splitting-require/#chunkname),一个特殊的注释语法来提供chunk name(需要webpack > 2.4)
标点（发现问题比较多，要不后面统一再换吧）

2017-10-02 16:49 UTC, Justineo commented on docs/zh-cn/advanced/data-fetching.md
> +- **导航完成之前获取**：导航完成前，在路由进入的拦截中获取数据，在数据获取成功后执行导航。
下同

2017-10-02 16:49 UTC, Justineo commented on docs/zh-cn/advanced/scroll-behavior.md
> +如果返回一个 falsy 的值，或者是一个空对象，那么不会发生滚动。
要注么

2017-10-02 16:49 UTC, Justineo commented on docs/zh-cn/api/router-instance.md
> +  动态的导航到一个新 url。参考[编程式导航](../essentials/navigation.md)。
URL

2017-10-02 16:49 UTC, Justineo commented on docs/zh-cn/api/router-instance.md
> +  该方法把一个回调排队，在路由完成初始导航时调用，这意味着它可以解析所有的异步进入钩子和路由初始化相关联的异步组件。
把一个回调函数加入队列？

2017-10-02 16:49 UTC, Justineo commented on docs/zh-cn/api/router-link.md
> +- **exact-active-class**
额外的激活 class

2017-10-02 16:49 UTC, Justineo commented on docs/zh-cn/api/router-link.md
> +  配置当链接被精确匹配的时候应该激活的 CSS class。注意默认值也是可以通过路由构造函数选项 `linkExactActiveClass` 进行全局配置的。
CSS class &rarr; class，下同

2017-10-02 16:49 UTC, Justineo commented on docs/zh-cn/api/router-link.md
> +###  将"激活时的 CSS class 应用在外层元素
将激活 class 应用在外层元素？

2017-10-02 16:49 UTC, Justineo commented on docs/zh-cn/api/router-link.md
>  有时候我们要让 "激活时的CSS类名" 应用在外层元素，而不是 `<a>` 标签本身，那么可以用 `<router-link>` 渲染外层元素，包裹着内层的原生 `<a>` 标签：
激活时的 CSS 类名 &rarr; 激活 class？

我们好像要考虑下这个 class 要不要翻译成类名

2017-10-02 16:49 UTC, Justineo commented on docs/zh-cn/essentials/history-mode.md
> +
其他代码示例都用的单引号，这个是不是 en 里也要改一下

2017-10-02 16:49 UTC, Justineo commented on docs/zh-cn/essentials/named-routes.md
> +完整的例子请[戳这里](https://github.com/vuejs/vue-router/blob/next/examples/named-routes/app.js)。
“在这里”？和 named-view 里保持一致。

2017-10-02 16:49 UTC, Justineo commented on docs/zh-cn/essentials/nested-routes.md
> +提供以上案例的可运行代码，[戳这里](https://jsfiddle.net/yyx990803/L7hscd8h/)。
同上

2017-10-03 04:01 UTC, Jinjiang commented on docs/zh-cn/SUMMARY.md
> +> 注意: vue-router@2.x 只适用于 Vue 2.x。0.7.x 版本的文档在[这里](https://github.com/vuejs/vue-router/tree/1.0/docs/zh-cn)。
历史原因，1.0 没发就跳 2.0 了，大家已经接受这件事了🤣

2017-10-03 04:14 UTC, Jinjiang commented on docs/zh-cn/advanced/lazy-loading.md
>  有时候我们想把某个路由下的所有组件都打包在同个异步块(chunk)中。只需要使用 [命名 chunk](https://webpack.js.org/guides/code-splitting-require/#chunkname),一个特殊的注释语法来提供chunk name(需要webpack > 2.4)
恩，我先把改到的地方都顺手改了，包括结尾没有句号的情况也比较多

2017-10-03 04:15 UTC, Jinjiang commented on docs/zh-cn/advanced/scroll-behavior.md
> +如果返回一个 falsy 的值，或者是一个空对象，那么不会发生滚动。
加上了

2017-10-03 04:17 UTC, Jinjiang commented on docs/zh-cn/api/router-instance.md
> +  该方法把一个回调排队，在路由完成初始导航时调用，这意味着它可以解析所有的异步进入钩子和路由初始化相关联的异步组件。
“queue a task/callback”直译比较晦涩，W3C 的 spec 里也经常出现这个词汇。想尽量描述得通俗一点，所以用了“排队”。我可能还是觉得排队好一些。

2017-10-03 04:20 UTC, Jinjiang commented on docs/zh-cn/api/router-link.md
>  有时候我们要让 "激活时的CSS类名" 应用在外层元素，而不是 `<a>` 标签本身，那么可以用 `<router-link>` 渲染外层元素，包裹着内层的原生 `<a>` 标签：
就 class 我觉得 OK

2017-10-03 04:23 UTC, Jinjiang commented on docs/zh-cn/essentials/named-routes.md
> +完整的例子请[戳这里](https://github.com/vuejs/vue-router/blob/next/examples/named-routes/app.js)。
我在别的文档里都译成“移步这里”了

2017-10-03 04:27 UTC, Jinjiang commented on docs/zh-cn/essentials/history-mode.md
> +
Done

2017-10-03 04:27 UTC, Jinjiang commented on docs/zh-cn/api/router-link.md
> +- **exact-active-class**
Done

2017-10-03 04:28 UTC, Jinjiang commented
都处理了一遍，有劳再 review：）

2017-10-03 04:34 UTC, Jinjiang commented on docs/zh-cn/advanced/lazy-loading.md
> +第二，在 webpack 2 中,我们可以使用[动态 import](https://github.com/tc39/proposal-dynamic-import)语法来定义代码分块点 (split point):
英文版也是这样的，我同步提了一个 PR #1780

2017-10-03 14:18 UTC, Justineo approved these changes

2017-10-03 15:09 UTC, Jinjiang commented on docs/zh-cn/advanced/lazy-loading.md
> +第二，在 webpack 2 中,我们可以使用[动态 import](https://github.com/tc39/proposal-dynamic-import)语法来定义代码分块点 (split point):
对面的 PR 中对开头字母大写提出了异议，我稍微看了一下它的官网，似乎还真都是小写的。待我稍作确认。

2017-10-03 15:15 UTC, merged