[Doc FR]: last changes and complete additional review.
vuejs/vue-router pull request #1776
Opened 2017-09-30 14:39 UTC by Haeresis

Hi @posva !

Here you will find the last changes added to french translation and a lot of typo fixes by a @rspt review.

Ready for merge in our side.

2017-09-30 15:34 UTC, posva requested changes
Pourquoi tu as enleve les accent circonflexes des mots chaine? les deux sont valides

2017-09-30 15:34 UTC, posva commented on docs/fr/api/options.md
> +  Permets de spécifier des fonctions personnalisées pour formater en objet ou en chaîne de caractères la requête. Surcharge les fonctions par défaut.
permettent non?

2017-09-30 15:34 UTC, posva commented on docs/fr/api/router-instance.md
> +  Permets d'ajouter dynamiquement des routes au routeur. L'argument doit être un tableau utilisant le même format de configuration que l'option `routes` du constructeur.
permet?

2017-10-01 07:44 UTC, Haeresis commented
Nous uniformisons l'orthographe de toutes les doc à la réforme de 1990 sur l'orthographe des mots français.

https://fr.m.wikipedia.org/wiki/Rectifications_orthographiques_du_français_en_1990

Je regarde pour les mots que tu as pointé (moins facile sur mobile :p)

2017-10-01 07:55 UTC, Haeresis commented on docs/fr/api/options.md
> +  Permets de spécifier des fonctions personnalisées pour formater en objet ou en chaîne de caractères la requête. Surcharge les fonctions par défaut.
J'avoue. Peut etre pour lever le doute on devrait mettre "et" à la place de /

2017-10-01 07:55 UTC, Haeresis commented on docs/fr/api/router-instance.md
> +  Permets d'ajouter dynamiquement des routes au routeur. L'argument doit être un tableau utilisant le même format de configuration que l'option `routes` du constructeur.
Exact. @rspt ? Une règle particulière ici ?

2017-10-01 08:02 UTC, rspt commented on docs/fr/api/options.md
> +  Permets de spécifier des fonctions personnalisées pour formater en objet ou en chaîne de caractères la requête. Surcharge les fonctions par défaut.
Je suis pour "Permettent"!

(et visiblement j'ai oublié le "chaîne" ici ainsi qu'à d'autres endroits, je ferais une autre PR)

2017-10-01 08:02 UTC, rspt commented on docs/fr/api/router-instance.md
> +  Permets d'ajouter dynamiquement des routes au routeur. L'argument doit être un tableau utilisant le même format de configuration que l'option `routes` du constructeur.
Pour moi il faut utiliser l'impératif dans ce contexte

2017-10-01 11:07 UTC, posva commented on docs/fr/api/router-instance.md
> +  Permets d'ajouter dynamiquement des routes au routeur. L'argument doit être un tableau utilisant le même format de configuration que l'option `routes` du constructeur.
Gardons plutôt la 3eme du sing, elle est utilisé partout et utiliser de l'impératif ne rends pas la documentation plus clair

2017-10-01 11:26 UTC, Haeresis commented on docs/fr/api/router-instance.md
> +  Permets d'ajouter dynamiquement des routes au routeur. L'argument doit être un tableau utilisant le même format de configuration que l'option `routes` du constructeur.
Je suis d'accord avec @posva. Et je ne pense pas que l'impératif sois justifié. "Permet de' c'est pareil que "Il permet de". D'ailleurs le fait qu'on mette "permettent" serait inconsistant.

2017-10-01 11:28 UTC, Haeresis commented on docs/fr/api/router-instance.md
> +  Permets d'ajouter dynamiquement des routes au routeur. L'argument doit être un tableau utilisant le même format de configuration que l'option `routes` du constructeur.
Je veux dire permettent est définitivement pas de l'impératif, tu nous et vous seulement

2017-10-01 12:01 UTC, rspt commented on docs/fr/api/router-instance.md
> +  Permets d'ajouter dynamiquement des routes au routeur. L'argument doit être un tableau utilisant le même format de configuration que l'option `routes` du constructeur.
Effectivement, il faudrait aligner tous les verbes si l'on veut être cohérent et ça ne rend pas forcément la doc plus claire.

Par contre d'un point de vue purement technique, l'absence de sujet direct dans la phrase requiert l'impératif.

Du coup les choix sont:
1. Utilisation du présent (version actuelle)
1. Utilisation de l'impératif (qui serait à mon avis plus correcte, mais un peu plus lourd)
1. Ajout du sujet dans la phrase (je trouverais ça dommage et beaucoup plus lourd).

Utiliser le choix 1 me convient, car on comprend que le sujet de la phrase est la fonction et ça permet d'empêcher la redondance.

2017-10-01 14:48 UTC, posva commented on docs/fr/api/router-instance.md
> +  Permets d'ajouter dynamiquement des routes au routeur. L'argument doit être un tableau utilisant le même format de configuration que l'option `routes` du constructeur.
l'option 1 est quand meme la plus pragmatique

2017-10-01 15:36 UTC, rspt commented on docs/fr/api/router-instance.md
> +  Permets d'ajouter dynamiquement des routes au routeur. L'argument doit être un tableau utilisant le même format de configuration que l'option `routes` du constructeur.
Oui je suis tout à fait d'accord!

Qui fait la modif @Haeresis ?

2017-10-02 07:07 UTC, Haeresis commented
Bien vu @posva. C'est rectifié.

2017-10-02 07:07 UTC, rspt approved these changes

2017-10-02 16:09 UTC, posva approved these changes

2017-10-02 16:10 UTC, merged