[en] typos
vuejs/vue-router pull request #1780
Opened 2017-10-03 04:33 UTC by Jinjiang

Changes:

1. "webpack" -> "Webpack"
2. change double quotes into single quotes in code snippets about "native Node.js" in `history-mode.md`, just because the others all use single quotes.

Thanks.

2017-10-03 14:53 UTC, posva requested changes
It's actually webpack with a lowercase w

2017-10-03 15:06 UTC, Jinjiang commented
Sorry for the changes without confirmation. But I found many "Webpack" with uppercases in other docs like `vue-loader`. So please don't mind me to make sure which is the right one. 😅
If the letter "w" should be lowercase. I will revert them above and fix the other docs.
Thanks.

2017-10-03 15:19 UTC, posva commented
@Jinjiang no worries! 👌

2017-10-03 15:35 UTC, Jinjiang commented
I had a check. The word in official website of webpack are all with lowercases. So I think the lowercase is right.
I only left one place with uppercase which is the first word of a sentence. I guess this should be changed.

2017-10-03 15:46 UTC, posva commented
It should also be lowercase when it's the first word in the sentence 😆 (https://webpack.js.org/support/#cto-s-vps-owners). Don't worry, I changed it

2017-10-03 15:47 UTC, posva approved these changes

2017-10-03 15:49 UTC, merged

2017-10-09 09:01 UTC, JounQin commented on docs/en/essentials/history-mode.md
> +      console.log('We cannot open 'index.htm' file.')
It should be `"index.htm" actually`.