Starting portuguese (pt-br) translation
vuejs/vue-router pull request #2081
Opened 2018-02-28 18:50 UTC by felipe-developer

2018-02-28 21:57 UTC, felipe-developer commented
Documentation translated into Portuguese. I count on the help of our employees to improve even more.

2018-03-01 14:49 UTC, felipe-developer commented
Documentation translated into Portuguese. I count on the help of our employees to improve even more.
-
@posva it's correct?

2018-03-01 15:31 UTC, posva commented
Hello, thanks a lot for the contribution! I'll do a general pass but I don't speak Portuguese, so I'll like to have a second eye read through the documentation

2019-01-03 00:22 UTC, angeliski requested changes

2019-01-03 00:22 UTC, angeliski commented on docs/pt-br/advanced/data-fetching.md
> +    // fetch the data when the view is created and the data is
It would be cool to translate the comments too

2019-01-03 00:22 UTC, angeliski commented on docs/pt-br/advanced/data-fetching.md
> +Com essa abordagem, buscamos os dados antes de navegar para o novo
Would be more clear 'navegar para **a nova rota**'

2019-01-03 00:22 UTC, angeliski commented on docs/pt-br/advanced/data-fetching.md
> +# Data Fetching
It would be cool to translate the section title

2019-01-03 00:22 UTC, angeliski commented on docs/pt-br/advanced/navigation-guards.md
> +Lembre-se de que **params or query changes won't trigger enter/leave navigation guards**. Você pode [assistir o objeto `$route`](../essentials/dynamic-matching.md#reacting-to-params-changes) para rea
I believe you forget the translate for **params or query changes won't trigger enter/leave navigation guards**

2019-01-03 00:22 UTC, angeliski commented on docs/pt-br/advanced/navigation-guards.md
> +Global antes que os guardas sejam chamados na ordem de criação, sempre que uma navegação é desencadeada. Os guardas podem ser resolvidos de forma assíncrona, e a navegação é considerada **pendente**
The paragraph 'Global antes que os guardas sejam chamados na ordem de criação' it's a litle confuse. What do you think to change to something like 'Guardas globais beforeEach são chamados na ordem de criação'. Make sense?

2019-01-03 00:22 UTC, angeliski commented on docs/pt-br/advanced/navigation-guards.md
> +- **`to: Route`**: the target [Route Object](../api/route-object.md) being navigated to.
I believe you forget the translate for **the target [Route Object](../api/route-object.md) being navigated to.**

2019-01-03 00:22 UTC, angeliski commented on docs/pt-br/advanced/navigation-guards.md
> +- **`from: Route`**: a rota atual sendo navegada de distância.
The paragraph 'a rota atual sendo navegada de distância' it's a litle confuse. What do you think to change to somenthing like 'a rota atual de qual a navegação está vindo'. Make sense?

2019-01-03 00:22 UTC, angeliski commented on docs/pt-br/advanced/navigation-guards.md
> +  - **`next(false)`**: abort the current navigation. If the browser URL was changed (either manually by the user or via back button), it will be reset to that of the `from` route.
I believe you forget the translate for **abort the current navigation. If the browser URL was changed (either manually by the user or via back button), it will be reset to that of the `from` route.**

2019-01-03 00:22 UTC, angeliski commented on docs/pt-br/advanced/navigation-guards.md
> +  - **`next(error)`**: (2.4.0+) se o argumento passou para `next` é uma instância de `Error`, ta navegação será interrompida e o erro será passado para callbacks registrados via [`router.onError()`](
I believe is better change **uma instância de `Error`, ta navegação será** to _uma instância de `Error`, **a** navegação será_

2019-01-03 00:22 UTC, angeliski commented on docs/pt-br/advanced/navigation-guards.md
> +O guarda `beforeRouteEnter` não **NÃO** tem acesso a `this`, porque o guarda é chamado antes que a navegação seja confirmada, então o novo componente de entrada ainda não foi criado.
Twice **não** in the translate

2019-01-03 00:22 UTC, angeliski commented on docs/pt-br/advanced/navigation-guards.md
> +No entanto, você pode acessar a instância passando um retorno de chamada para `próximo`. O retorno de chamada será chamado quando a navegação for confirmada e a instância do componente será passada p
I believe is better not translate the function name **next** to próximo. Maybe can cause confuse

2019-01-03 00:22 UTC, angeliski commented on docs/pt-br/advanced/navigation-guards.md
> +Tenha em atenção que `beforeRouteEnter` é o único guarda que aceita passar uma chamada de retorno para `next`. Para `beforeRouteUpdate` e `beforeRouteLeave`, `this` já está disponível, então passar u
Maybe is better change the **Tenha em atenção** to **Tenha atenção**

2019-01-03 00:22 UTC, angeliski commented on docs/pt-br/advanced/navigation-guards.md
> +2. Ligar deixar guardas em componentes desativados. (Call leave guards in deactivated components)
Maybe we can remove the english from here?

2019-01-03 00:22 UTC, angeliski commented on docs/pt-br/advanced/transitions.md
> +[Tudo sobre `<transition>`] (https://vuejs.org/guide/transitions.html) funciona o mesmo aqui.
I believe is better change to **[Toda a transition API] (https://vuejs.org/guide/transitions.html) funciona aqui.**

2019-01-03 00:22 UTC, angeliski commented on docs/pt-br/advanced/transitions.md
> +O uso acima usará a mesma transição para todas as rotas. Se você deseja que o componente de cada rota tenha transições diferentes, você pode usar `<transição>` com nomes diferentes dentro de cada com
I believe is better not translate the function name transition to transição. Maybe can cause confuse

2019-01-03 00:22 UTC, angeliski commented on docs/pt-br/api/component-injections.md
> +   Atual ativa [Route](route-object.md). Esta propriedade é somente leitura e suas propriedades são imutáveis, mas podem ser vistas.
I believe is better change **Atual ativa [Route]** to **A [rota] atual que está ativa**

2019-01-03 00:22 UTC, angeliski commented on docs/pt-br/api/router-instance.md
> +  A instância do root Vue, o `router` oi injetado.
I believe is better change **o `router` oi injetado** to **onde o `router` foi injetado**

2019-01-03 00:22 UTC, angeliski commented on docs/pt-br/api/router-link.md
> +`<router-link>` é o componente para permitir a navegação do usuário em um aplicativo habilitado para roteador. A localização do destino é especificada com o `to` prop. Ele é como uma marca `<a>` com
I believe is better change **é especificada com o `to` prop** to **é especificada com a propriedade `to`**

2019-01-03 00:22 UTC, angeliski commented on docs/pt-br/api/router-link.md
> +`<roteador-link>` é preferido em relação a `<a href="...">` codificado por pelos seguintes motivos:
I believe is better not translate the component name router-link to roteador-link. Maybe can cause confuse

2019-01-03 00:22 UTC, angeliski commented on docs/pt-br/api/router-link.md
> +  Indica a rota de destino do link. Quando clicado, o valor do `to` prop será passado para `router.push ()` internamente, então o valor pode ser uma string ou um objeto descritor de localização.
I believe is better change **o valor do `to` prop** to **o valor da propriedade `to`**

2019-01-03 00:26 UTC, angeliski commented
Hey @felipe-ssilva Great work! I will help when is possible. I started the review as suggested by @posva
Tomorrow I will finish the last files

Hey @posva when we finish that review, you can merge that or do will need another revisor?

Cheers

2019-01-03 01:07 UTC, felipe-ssilva commented
Thanks @angeliski !

2019-01-03 22:57 UTC, angeliski requested changes
Done @felipe-ssilva !
I reviewed the last files and put some observations. I believe you can in general don't translate name components and functions (e.g. `<router-view>`, next), but It would be cool to translate sections titles and comments.
If you need some help, let me know

Cheers

2019-01-03 22:57 UTC, angeliski commented on docs/pt-br/api/router-view.md
> +### Props
Is better change to **Propriedades**

2019-01-03 22:57 UTC, angeliski commented on docs/pt-br/api/router-view.md
> +### Behavior
I doesn't find this section in the original. Do you added here?

2019-01-03 22:57 UTC, angeliski commented on docs/pt-br/essentials/dynamic-matching.md
> +Além de `$route.params`, o `$route` O objeto também expõe outras informações úteis, como `$route.query` (se houver uma consulta na URL), `$route.hash`, etc. Você pode verificar os detalhes completos
I believe is better change **o `$route` O objeto** to **o objeto `$route`**

2019-01-03 22:57 UTC, angeliski commented on docs/pt-br/essentials/dynamic-matching.md
> +`vue-router` Use [path-to-regexp](https://github.com/pillarjs/path-to-regexp) como seu mecanismo de correspondência de trilhas, por isso ele suporta muitos padrões de correspondência avançados, como
I believe is better change  **`vue-router` Use** to **`vue-router` usa**

2019-01-03 22:57 UTC, angeliski commented on docs/pt-br/essentials/dynamic-matching.md
> +`vue-router` Use [path-to-regexp](https://github.com/pillarjs/path-to-regexp) como seu mecanismo de correspondência de trilhas, por isso ele suporta muitos padrões de correspondência avançados, como
I believe is better change **correspondência de trilhas** to **correspondência de rotas**

2019-01-03 22:57 UTC, angeliski commented on docs/pt-br/essentials/named-routes.md
> +Para vincular a uma rota nomeada, você pode passar um objeto para o `router-link` componentes `to` prop:
I believe is better change  **um objeto para o `router-link` componentes `to` prop:** to **um objeto para o componente `router-link` através da propriedade `to`**

2019-01-03 22:57 UTC, angeliski commented on docs/pt-br/essentials/navigation.md
> +This is the method called internally when you click a `<router-link>`, so clicking `<router-link :to="...">` is the equivalent of calling `router.push(...)`.
I believe you forget remove

2019-01-03 22:57 UTC, angeliski commented on docs/pt-br/essentials/navigation.md
> +In 2.2.0+, optionally provide `onComplete` and `onAbort` callbacks to `router.push` or `router.replace` as the 2nd and 3rd arguments. These callbacks will be called when the navigation either success
I believe you forget remove

2019-01-03 22:57 UTC, angeliski commented on docs/pt-br/essentials/nested-routes.md
> +Como você pode ver, a opção `children` é apenas outra matriz de objetos de configuração de rotas como `routes`  em si. Portanto, você pode manter as visualizações de nidificação tanto quanto você pre
I believe is better change **visualizações de nidificação** to **visualizações de aninhamento**

2019-01-03 22:57 UTC, angeliski commented on docs/pt-br/essentials/passing-props.md
> +Quando `props` é definido como `true`, o `route.params` será configurado como o componente adereços.
I believe is better change **como o componente adereços.** to **como as propriedades do componente**

2019-01-03 22:57 UTC, angeliski commented on docs/pt-br/essentials/passing-props.md
> +Você pode criar uma função que retorna adereços. Isso permite que você elimine parâmetros em outros tipos, combine valores estáticos com valores baseados na rota, etc.
I believe is better change **retorna adereços** to **retorna propriedades**

2019-01-03 22:57 UTC, angeliski commented on docs/pt-br/essentials/passing-props.md
> +A URL `/search?q=vue` assaria `{query: 'vue'}` como adereços para o componente `SearchUser`.
I believe is better change **assaria `{query: 'vue'}` como adereços para** to **passaria `{query: 'vue'}` como propriedade para**

2019-01-04 11:10 UTC, posva commented
Com licença! Eu esqueci deste PR mas a tradução está em outro repositório: https://github.com/vuejs-br/vue-router
Eu gostaria que vocês conferissem com eles e ajudassem nesse repositório

Acho que o @ErickPetru precisa de ajuda no repositório.

In order for the translation to get merged into vue-router, we need to see there is an active team keeping up to date with new versions like the Japanese, Chinese, French, Russian and Korean translators do. They use a tool to get updates but I cannot remember the name of the tool right now. Once you have that, please come back so we can add the Portuguese translation here 🙂

2019-01-04 11:10 UTC, closed without merging

2019-01-04 11:18 UTC, angeliski commented
No problem @posva ! 
I will help @ErickPetru in the other repository.

Thank's for your help