migrating from gitbooks
vuejs/vue-router pull request #2224
Opened 2018-05-27 15:37 UTC by nicedchy

This PR is`lang-ja` docs migrating to vuepress

2018-05-27 16:26 UTC, kazupon requested changes
`/dist/*.js` 配下のファイルも更新してしまっているので、それはrevertしてください。 🙏 

これらは、リリースされるときにビルドされるものです。

2018-05-28 01:25 UTC, nicedaichi3 commented
@kazupon 
レビューありがとうございます
docs を build したところ更新されていたようでした。
`/dist/*.js` のファイルを前回のコミットまで revert していますので再度レビューお願いします 🙏

2018-05-28 01:29 UTC, kazupon approved these changes

2018-05-28 01:31 UTC, merged

2018-05-28 01:32 UTC, kazupon commented
Thanks!