TypeScript: Expose a `Next` type
vuejs/vue-router pull request #2497
Opened 2018-11-25 07:03 UTC by beary

Expose a `Next` type for this usage:
```typescript
// ...
import { Route, Next } from 'vue-router'

@Component
export default class Verify extends Vue {
  // ...
  private beforeRouteEnter(to: Route, from: Route, next: Next) {
    next(vm => {
      vm.$data.username = decodeURIComponent(to.query.username || '')
    })
  }
}
```

2019-02-17 12:08 UTC, kevlarr commented
Exactly the PR I was about to submit.. @posva How do PRs get reviewed/merged?

2019-02-17 13:16 UTC, posva commented
I will come at it when I have time, after other Bugs and features

2019-03-18 17:05 UTC, voool commented
As a workaround, to grab the `next` interface with Typescript you can do `Parameters<NavigationGuard>[2]`

2019-03-19 11:33 UTC, kevlarr commented
Nice @voool, that's really clean! I didn't know that was possible - I've been copying the type def into my own code, which is more verbose and also more brittle (in case the def changes at all).

2019-05-01 13:50 UTC, andredewaard commented
Any progress on when this will be merged?

2019-09-12 05:36 UTC, faustbrian commented
@posva any progress on this?

2020-04-28 08:45 UTC, d2phap commented
Any update?

2020-05-11 07:39 UTC, posva requested changes
I'm renaming the type to match vue-router-next
One thing that is problematic is that only `beforeRouteEnter`'s `next` allows a callback. So I think we should export a type without the callback and make a specific type for `beforeRouteEnter` where we change `next` to include `(vm: V) => any`

2020-05-11 07:39 UTC, posva commented on types/router.d.ts
> +export type Next<V extends Vue = Vue> = (to?: RawLocation | false | ((vm: V) => any) | void) => void;
```suggestion
export type NavigationGuardNext<V extends Vue = Vue> = (to?: RawLocation | false | ((vm: V) => any) | void) => void;
```

2020-05-11 07:39 UTC, posva commented on types/index.d.ts
> +  Next
```suggestion
  NavigationGuardNext
```

2020-05-11 07:39 UTC, posva commented on types/router.d.ts
> +  next: Next<V>
```suggestion
  next: NavigationGuardNext<V>
```

2020-05-11 07:47 UTC, beary reviewed
Looks good :smiley:

2020-05-11 08:03 UTC, beary reviewed
:+1:

2020-05-11 08:07 UTC, beary commented
I am not familiar with the operation of pr, if it interferes with people, I am sorry.
Or if the commit record is too confusing, you can close this pull request and create a new one.

2020-05-11 08:17 UTC, posva commented
No worries for the commit history @beary, we squash commits at the end! Let me know if this is things are not clear and I will finish this up

2020-05-11 08:25 UTC, beary commented
@posva 
I read your changes, I think it is very good, And there is nothings I need to add!

2020-05-11 08:28 UTC, posva commented
@beary There is a change left: https://github.com/vuejs/vue-router/pull/2497#pullrequestreview-408928568

2020-05-11 08:30 UTC, beary reviewed
Reviewed

2020-05-11 08:39 UTC, beary reviewed
I submitted it for review, but it is still in a reviewable state

2020-05-11 08:45 UTC, posva requested changes
One thing that is problematic is that only `beforeRouteEnter`'s `next` allows a callback. So I think we should export a type without the callback and make a specific type for `beforeRouteEnter` where we change `next` to include `(vm: V) => any`

2020-05-11 08:45 UTC, posva commented
@beary because the review is the same

2020-05-11 08:47 UTC, beary reviewed
Reviewed

2020-05-11 08:50 UTC, posva commented
what? see https://github.com/vuejs/vue-router/pull/2497#pullrequestreview-408976579
if you don't see where to add, that's fine, just let me know and I will pick it but let's not go in circles and waste each other time

2020-05-11 08:55 UTC, beary commented
@posva 
Sorry I couldn't add it recently

2020-05-11 08:59 UTC, merged