docs: add more details to resolution flow
vuejs/vue-router pull request #2710
Opened 2019-04-12 13:17 UTC by pot-code

原文是“用创建好的实例调用 `beforeRouteEnter` 守卫中传给 `next` 的回调函数”，用创建好的什么实例？路由实例？

英文为“Call callbacks passed to `next` in `beforeRouteEnter` guards with instantiated instances”，我认为 call...with 应该是使用其作为调用 callback 参数的意思，而不是用它来调用 callback

2019-04-12 13:20 UTC, posva commented on docs/zh/guide/advanced/navigation-guards.md
> +12. 调用 `beforeRouteEnter` 守卫中传给 `next` 的回调函数，被激活的组件实例会作为回调函数的参数传入
```suggestion
12. 调用 `beforeRouteEnter` 守卫中传给 `next` 的回调函数，被激活的组件实例会作为回调函数的参数传入。
```

2019-04-12 13:21 UTC, posva commented
Where is this coming from? Is this also missing in English docs. Translation doesn't give me something readable 🙁 @justineo

2019-04-13 16:53 UTC, Justineo requested changes

2019-04-13 16:53 UTC, Justineo commented on docs/zh/guide/advanced/navigation-guards.md
> +12. 调用 `beforeRouteEnter` 守卫中传给 `next` 的回调函数，被激活的组件实例会作为回调函数的参数传入
```suggestion
12. 调用 `beforeRouteEnter` 守卫中传给 `next` 的回调函数，创建好的组件实例会作为回调函数的参数传入。
```

2019-04-13 16:56 UTC, Justineo commented
@posva It's clarifying what “with instantiated instances” mean. Basically it's saying: the instantiated instances will serve as the argument of `next`'s callback function.

2020-08-03 10:15 UTC, merged