docs(zh): updated
vuejs/vue-router pull request #2903
Opened 2019-08-23 09:53 UTC by Jinjiang

Ref: https://github.com/vuejs/vue-router/compare/e05631d...e0d4dc4
/ping @Justineo 
Thanks.

2019-08-23 10:17 UTC, Justineo requested changes

2019-08-23 10:17 UTC, Justineo commented on docs/zh/api/README.md
> +`router-link` 通过一个[作用域插槽](https://cn.vuejs.org/v2/guide/components-slots.html#作用域插槽)暴露低级别低的定制能力。这是一个更高阶的 API，主要面向库作者，但也可以为开发者提供便利，多数情况用在一个类似 _NavLink_ 或其它组件里。
```suggestion
`router-link` 通过一个[作用域插槽](https://cn.vuejs.org/v2/guide/components-slots.html#作用域插槽)暴露底层的定制能力。这是一个更高阶的 API，主要面向库作者，但也可以为开发者提供便利，多数情况用在一个类似 _NavLink_ 这样的组件里。
```

2019-08-23 10:17 UTC, Justineo commented on docs/zh/api/README.md
> +- `route`：解析后的正常化的地址。
normalize 目前约定的是“[规范化](https://github.com/vuejs/cn.vuejs.org/wiki)”，这里要用吗？

2019-08-23 10:17 UTC, Justineo commented on docs/zh/api/README.md
> +- `isActive`：如果需要应用 [active class](#active-class) 则为 `true`。允许应用一个任意的 class。
后文用的是“激活 class”，这里保持一致？

2019-08-23 10:17 UTC, Justineo commented on docs/zh/api/README.md
> +- `isExactActive`：：如果需要应用 [exact active class](#exact-active-class) 则为 `true`。允许应用一个任意的 class。
同上

2019-08-23 10:17 UTC, Justineo commented on docs/zh/api/README.md
> +有的时候我们可能想把激活的 class 应用到一个外部元素而不是 `<a>` 标签本身，这时你可以在一个 `router-link` 中包裹该元素并使用 `v-slot` property 来创建链接：
```suggestion
有的时候我们可能想把激活 class 应用到一个外部元素而不是 `<a>` 标签本身，这时你可以在一个 `router-link` 中包裹该元素并使用 `v-slot` property 来创建链接：
```

2019-08-23 10:17 UTC, Justineo commented on docs/zh/api/README.md
> +有的时候我们可能想把激活的 class 应用到一个外部元素而不是 `<a>` 标签本身，这时你可以在一个 `router-link` 中包裹该元素并使用 `v-slot` property 来创建链接：
BTW. `v-slot` property 这样翻理解上会不会有困难？

2019-08-25 08:53 UTC, Jinjiang commented on docs/zh/api/README.md
> +- `isActive`：如果需要应用 [active class](#active-class) 则为 `true`。允许应用一个任意的 class。
统一成了“激活的 class”和“精确激活的 class”如何？

2019-09-02 03:54 UTC, Justineo approved these changes

2019-09-02 07:29 UTC, merged

2019-09-02 07:30 UTC, posva commented
Thanks to the both of you! 💚