chore: upgrade path-to-regexp to v1.8.0 (resolves #2924)
vuejs/vue-router pull request #3032
Opened 2019-11-18 14:21 UTC by pimlie

See issue #2924 and the commit messages.

The server host configuration commit could be omitted but I'm running Node on a remote docker cluster which means I need to set the host to `0.0.0.0`. To be able to run the e2e tests I actually also needed to add `'no-sandbox', 'headless', 'disable-gpu', 'disable-dev-shm-usage'` to `chromeOptions.args` in `test/e2e/nightwatch.config.js`. Otherwise Chrome wont be able to start in a docker container.

2019-11-18 15:44 UTC, posva requested changes
Thanks! Could you move the test to a new one and also add a test that checks that case sensitive when the option is specified and that  params do not match?

2019-11-18 17:49 UTC, pimlie commented
> that checks that case sensitive when the option is specified

Hmm, I dont seem to have access to _RouteConfig.caseSensitive_ in _normalizeLocation_ as that only receives a _Route_ type. Would it be ok to add the normalized [`pathToRegexpOptions`](https://github.com/vuejs/vue-router/blob/dev/src/create-route-map.js#L80) to the _RouteRecord_ type?

2019-11-20 08:45 UTC, posva commented
Ah right, it will need a test using the Router instance instance instead let's cover it that way for the moment

2019-12-11 19:59 UTC, pimlie commented
Unfortunately I am not sure how I can use the Router instance to add a test for 2925. Could you elaborate a bit on what I should do?

2020-05-11 11:54 UTC, merged

2020-05-11 11:56 UTC, posva commented
I forgot about this one! I locally added a new test