Update type of Route.name (TS)
vuejs/vue-router pull request #3117
Opened 2020-02-06 22:41 UTC by rijkvanzanten

On very first load, `name` is `null`, not `string` or `undefined`. This means that either the passed route is wrong, or the type is incorrect.

2020-02-07 09:58 UTC, posva approved these changes
Yeah, only the initial location has a name of `null`

2020-02-07 09:58 UTC, posva requested changes
I forgot, can you fix the failing test?

2020-02-07 15:04 UTC, rijkvanzanten commented
Jumped into it too hastily before.. it's fixed now @posva 🙂

2020-02-07 15:31 UTC, merged

2020-02-07 15:31 UTC, posva commented
Thanks!

2020-03-06 07:39 UTC, zhuwenqi001 commented
after route allows name to be null, there will be such a problem in my project: 
`router.push` and `next` method error. Do other interfaces also need to be modified? Such as Routeconfig and Location
![15_37_58__03_06_2020](https://user-images.githubusercontent.com/25142129/76062427-a2ecaa00-5fc0-11ea-8750-23e8a87b5d79.jpg)
![2](https://user-images.githubusercontent.com/25142129/76062464-b6981080-5fc0-11ea-840e-49191716262a.jpg)

2020-03-06 09:25 UTC, LinusBorg commented
Appearantly so. Please open a new issue about this.

2020-03-06 15:48 UTC, posva commented
@zhuwenqi001 see https://github.com/vuejs/vue-router/issues/3139
In your case you can do `tab.name!` because you know that the name exists. I'm thinking that allowing `null` for `Location` shouldn't introduce any problem, so we could maybe allow it for convenience