Fix/find init location
vuejs/vue-router pull request #3125
Opened 2020-02-15 19:54 UTC by Alexeykhr

I will try to fix this :). Issue: https://github.com/vuejs/vue-router/issues/3103

The problem is url generation. We have 2 routes:

```
<router-link to="/special/tést1">/special/tést1</router-link>
<router-link :to="{ name: 'special', params: {word: 'tést2'} }">/special/tést2</router-link>
```

In the first case, the route is transmitted as it is. In the second - it is decoded through the library: `path-to-regexp` (in new versions this can be changed by parameter)

Before:
![1](https://user-images.githubusercontent.com/14747569/74594204-1e031600-503c-11ea-9810-593e744afbb4.png)

After:
![2](https://user-images.githubusercontent.com/14747569/74594203-1ba0bc00-503c-11ea-8b8e-632e466b577a.png)

But, if it works in **History Mode**. Then for **Hash Mode** you need to edit separately, because there the same problem exists.

[Somewhere here](https://github.com/vuejs/vue-router/blob/dev/src/history/hash.js#L128)

2020-02-16 14:51 UTC, posva requested changes
Thank you for the PR but this the fix shouldn't change how URLs are generated. The encoded version should be the one generated. The problem is the other way around: when the page is reloaded, the `fullPath` property is decoded (/user/tést) instead of being  encoded (/user/t%C3%A9st) like it usually is when doing `$router.push({ name: 'special', params: { test: 'tést' }})`

Regarding the difference between named routes and string-based push like `$router.push('/url')` and `$router.push({ path: '/url' })`: when doing string-based push, the user is responsible for encoding the urls but when doing others, the router should encode params for you. That's why the two router-link you added in the e2e test yield different results. But it's expected

You can change things in this pr if you want to or close it and start a new one

2020-02-16 19:39 UTC, Alexeykhr commented
Thanks for the detailed answer, if not against, I will try to solve it again.

Now encode fullPath strings are compared, and the user now encode his path (changed in tests)

![1](https://user-images.githubusercontent.com/14747569/74611205-7d2b5e00-5102-11ea-8c21-c9e155dc16ea.png)

2020-02-16 19:55 UTC, Alexeykhr commented
If I understood correctly, then I, as a user, should encode the string in the fallen test.

`<li><router-link to="/é">/é</router-link></li>`
to
`<li><router-link to="/%C3%A9">/é</router-link></li>`

2020-05-26 14:19 UTC, posva commented
@Alexeykhr I updated the original issue at https://github.com/vuejs/vue-router/issues/3103

Going to an unencoded URL is not valid, so it doesn't matter if the active link matches or not, but when visiting the encoded valid url, it should match the link

2020-11-05 15:14 UTC, closed without merging