feat(types): RouterConfig for multiple components (#3217)
vuejs/vue-router pull request #3218
Opened 2020-06-02 18:00 UTC by javiertury

Implements typings for #3217

The test demonstrates that with correct typings, typescript is able to infer that route is of type `Route` on its own.
```
             abc: route => route.params,
```

2020-06-03 09:02 UTC, posva requested changes
Thanks for this!

2020-06-03 09:02 UTC, posva commented on types/router.d.ts
> +export type RouteConfig = BaseRouteConfig & ({
can you instead create 2 interfaces `RouteConfigSingleView` and `RouteConfigMultipleViews` that extend the base config and export RouteConfig as the type union?

2020-06-03 09:02 UTC, posva commented on types/router.d.ts
> +interface BaseRouteConfig {
Let's change the name

```suggestion
interface _RouteConfigBase {
```

2020-06-03 15:10 UTC, javiertury commented
Done

2020-06-04 10:00 UTC, posva approved these changes
Thanks a lot. Let me just move the children next to components as well and I will merge this

2020-06-04 10:00 UTC, posva commented on types/router.d.ts
>    children?: RouteConfig[]
```suggestion
```

2020-06-04 10:00 UTC, posva commented on types/router.d.ts
> +  components?: Dictionary<Component>
```suggestion
  components?: Dictionary<Component>
  children?: RouteConfig[]
```

2020-06-04 10:31 UTC, merged

2020-06-18 16:32 UTC, andersbc commented
The associated commit broke my ts use case

I have a custom interface for my Router configuration, e.g.:

```ts
// file: routes.ts
// ...

interface MyRouteConfig extends RouteConfig {
  meta?: MyMeta; // <- defined elsewhere
}

export const routes: Array<MyRouteConfig> = [
  // ... the usual route configuration, with my added meta-thing
]

```

After the commit, the `RouteConfig` is now a union type, i.e.. `RouteConfig = RouteConfigSingleView | RouteConfigMultipleViews`

However, typescript can't extend from union types, because "An interface can only extend an object type or intersection of object types with statically known members" 

What I really need is to extends the new `RouteConfigMultipleViews` type, but it doesn't get exported. Any chance of exporting it? Thanks :-)

2020-06-19 10:18 UTC, javiertury commented
That was a case I missed.

They are trying to fix it in #3234. Personally I think that using a generic `RouteConfig<Meta = any>` [as proposed in this comment](https://github.com/vuejs/vue-router/issues/3234#issuecomment-644683914) is a good solution.

2020-06-19 11:02 UTC, posva commented
FYI, adding a generic to the type should go through an RFC because is not that simple of a change