fix(create-mathcer): remove duplicated decodeURIComponent
vuejs/vue-router pull request #3268
Opened 2020-07-28 19:14 UTC by claudiolcastro

So, checking this issue https://github.com/vuejs/vue-router/issues/2725
I found that removing the `decodeURIComponent` from the `matchRoute` kinda resolve the problem, because the param already comes decoded.

I don't know if this is the proper way to fix this issue, but I will give some examples below that worked for me:

**URL**: _/route-matching/params/%252520-working/bar_  

PS*: Check the `foo` param

**Without the fix**  :
![FAIL-route-matching_params_%252520-working_bar](https://user-images.githubusercontent.com/20761700/88710319-df927c80-d0ec-11ea-8178-99faebc41b7f.png)

**After the change:**
![WORK-route-matching_params_%252520-working_bar](https://user-images.githubusercontent.com/20761700/88710389-f933c400-d0ec-11ea-8eaa-4c136c28a4ba.png)

This example was also broking:
**URL**: /route-matching/params/100%25-working/bar"

![FAIL-route-matching_params_100%25-working_bar](https://user-images.githubusercontent.com/20761700/88710658-53348980-d0ed-11ea-9468-75e5370b4c4f.png)

2020-08-03 09:02 UTC, posva requested changes
Thanks for this! Let's add a few e2e tests to check this behavior in hash-mode.js and basic.js. One for initial navigation and a different one for a router-link navigation

You can check existing tests in those files as well

2020-09-10 08:10 UTC, mestevezdeister commented
Any new about this issue? Does it definitely fix the problem? I've tried applying the commit in my repository and it works for me. Is it going to be merge in the 3.x.x release? I've checked v3.4.3 and does not include the fix, the decoding problem still occurs.

Thank you very much!

2020-09-10 08:31 UTC, posva commented
It's missing tests if anybody is up to contribute!

2020-09-10 09:02 UTC, mestevezdeister commented
I don't know how to; but if I can and you can give me some guidance or refer me to some documentation about how to contribute in testing I would be glad to contribute.

2020-09-15 13:41 UTC, mestevezdeister commented
I've made the same modification and add the mentioned e2e tests in #3288

2020-09-29 13:15 UTC, closed without merging