types: Add RouteMeta interface to enable module augmentation
vuejs/vue-router pull request #3385
Opened 2020-11-24 13:42 UTC by HoldYourWaffle

I added a `RouteMeta` interface to the type declarations to allow for stronger type safety using [module augmentation](https://www.typescriptlang.org/docs/handbook/declaration-merging.html#module-augmentation).

For example:
```ts
declare module 'vue-router/types/router' {
    interface RouteMeta {
        x: string;
    }
}
```
Would define `myRoute.meta.x` to be a `string`. Non-existent properties will show an error.

Unfortunately this is a (minor) breaking change. As far as I know this can't be avoided without sacrificing the added type-safety.
Users can manually revert to the original "`any`" behavior using an augmentation like this:
```ts
declare module 'vue-router/types/router' {
    interface RouteMeta {
        [key: string]: any;
    }
}
```
I can't make this the default however, because it can't be _overwritten_ using module augmentation.
In other words: the "`any`"-index type would stay "active", thus defeating the purpose of added type-safety.

I hope this suggestion can be considered nonetheless.

2020-11-24 15:27 UTC, posva requested changes
Thanks, can you make like the existing one at https://github.com/vuejs/vue-router-next/pull/407 and add a test?

2020-11-24 16:37 UTC, HoldYourWaffle commented
@posva Although better than using plain `any`, I don't think having `RouteMeta` extend `Record<..., any>` is the best way here.
Like I mentioned in my initial comment, this kind of defeats the purpose of the added type safety.

It's better than nothing of course, since properties that have been declared will have their appropriate types.
However, invalid (undeclared) properties will not cause an error, meaning that things like typo's will go unnoticed.

Therefore I'd propose leaving this "Record extension" up to the user. Then anyone who wants to is free to have _their_ `RouteMeta` extend it, but it won't be _forced_ on all the others.

2020-11-24 17:21 UTC, posva commented
For Vue Router 3, that would be a breaking change, so we will have to keep `any`, but it can maybe be changed to unknown in v4 (vue-router-next)

2020-12-01 10:07 UTC, HoldYourWaffle commented
I suppose that's the only way then. I'll update this as soon as I get back to my workspace.
Should I create a PR to vue-router-next as well for changing `any` to `unknown`?

2020-12-01 10:14 UTC, posva commented
Sure! Let's see if existing tests pass and if the change is reasonable

2021-01-23 17:15 UTC, posva commented on types/router.d.ts
>  }
```suggestion
export interface RouteMeta extends Record<string | number | symbol, any> {}
```

2021-03-11 10:02 UTC, qwekelly commented
@posva hello, The problem still exists on vue-router@4.0.4，can you solve it ? thanks!
and vue-router@4.0.4 vue-router.d.ts still exists ：
`export declare interface RouteMeta extends Record<string | number | symbol, unknown> {
}`

2021-03-11 11:04 UTC, posva requested changes
The last thing that needs to be done here is to export `RouteMeta` from `index.d.ts` and add a test at https://github.com/vuejs/vue-router/tree/dev/types/test 🙂

2021-06-21 14:07 UTC, merged