docs(zh): translate navigation-failures.md to chinese.
vuejs/vue-router pull request #3416
Opened 2020-12-15 18:00 UTC by champkeh

2020-12-17 11:37 UTC, Justineo requested changes

2020-12-17 11:37 UTC, Justineo commented on docs/zh/guide/advanced/navigation-failures.md
> +_导航故障_，或者叫_导航失败_，表示一次失败的导航，原文 navigation failures，本文统一采用 _导航故障_。
中文使用 `*` 来标注斜体吧，可以不需要加额外的空格了。

2020-12-17 11:37 UTC, Justineo commented on docs/zh/guide/advanced/navigation-failures.md
> +- 用户已经位于他们正在尝试导航的页面了
```suggestion
- 用户已经位于他们正在尝试导航到的页面
```

2020-12-17 11:37 UTC, Justineo commented on docs/zh/guide/advanced/navigation-failures.md
> +当使用 `router-link` 组件时，**这些失败都不会打印出错误**。然而，如果你使用 `router.push` 或者 `router.replace` 的话，你可能就会在控制台看到一条 _"Uncaught (in promise) Error"_ 这样的错误，后面会跟着一条更具体的消息。让我们了解如何区分 _导航故障_。
```suggestion
当使用 `router-link` 组件时，**这些失败都不会打印出错误**。然而，如果你使用 `router.push` 或者 `router.replace` 的话，可能会在控制台看到一条 _"Uncaught (in promise) Error"_ 这样的错误，后面跟着一条更具体的消息。让我们来了解一下如何区分*导航故障*。
```

2020-12-17 11:37 UTC, Justineo commented on docs/zh/guide/advanced/navigation-failures.md
> +在 v3.2.0 中，通过使用 `router.push` 的两个可选的回调函数：`onComplete` 和 `onAbort` 来暴露 _导航故障_。从版本 3.1.0 开始，`router.push` 和 `router.replace` 在没有提供 `onComplete`/`onAbort` 回调的情况下会返回一个 _Promise_。用这个 _Promise_ 的 resolve 和
```suggestion
在 v3.2.0 中，可以通过使用 `router.push` 的两个可选的回调函数：`onComplete` 和 `onAbort` 来暴露*导航故障*。从版本 3.1.0 开始，`router.push` 和 `router.replace` 在没有提供 `onComplete`/`onAbort` 回调的情况下会返回一个*Promise*。这个*Promise*的 resolve 和 reject 将分别用来代替 `onComplete` 和 `onAbort` 的调用。
```

2020-12-17 11:37 UTC, Justineo commented on docs/zh/guide/advanced/navigation-failures.md
> +// trying to access the admin page
注释需要翻译一下，下同

2020-12-17 11:37 UTC, Justineo commented on docs/zh/guide/advanced/navigation-failures.md
> +如果你忽略第二个参数：`isNavigationFailure(failure)`，那么只会检查这个错误是不是一个 _导航故障_。(言外之意：不会检查它到底是哪一种导航故障)
翻译最好还是不要自己解释太多，改变原文的话最好给原文也提一下 PR。

2020-12-17 14:25 UTC, champkeh commented on docs/zh/guide/advanced/navigation-failures.md
> +_导航故障_，或者叫_导航失败_，表示一次失败的导航，原文 navigation failures，本文统一采用 _导航故障_。
好的，顺便问一下，我要怎么修改？是在我本地改完之后push吗？对pr流程还不是太熟悉[捂脸]

2020-12-18 06:13 UTC, Justineo requested changes

2020-12-18 06:13 UTC, Justineo commented on docs/zh/guide/advanced/navigation-failures.md
> +在 v3.2.0 中，可以通过使用 `router.push` 的两个可选的回调函数：`onComplete` 和 `onAbort` 来暴露*导航故障*。从版本 3.1.0 开始，`router.push` 和 `router.replace` 在没有提供 `onComplete`/`onAbort` 回调的情况下会返回一个*Promise*。这个*Promise*的 resolve 和 re
```suggestion
在 v3.2.0 中，可以通过使用 `router.push` 的两个可选的回调函数：`onComplete` 和 `onAbort` 来暴露*导航故障*。从版本 3.1.0 开始，`router.push` 和 `router.replace` 在没有提供 `onComplete`/`onAbort` 回调的情况下会返回一个 *Promise*。这个 *Promise* 的 resolve 和 reject 将分别用来代替 `onComplete` 和 `onAbort` 的调用。
```

2020-12-18 08:39 UTC, Justineo approved these changes

2020-12-18 08:49 UTC, merged

2020-12-18 08:50 UTC, posva commented
Thanks!