docs(zh): update
vuejs/vue-router pull request #3446
Opened 2021-01-13 06:08 UTC by huzhengen

add note about push
expose START_LOCATION
addRoute, getRoutes

2021-01-17 02:00 UTC, Jinjiang requested changes

2021-01-17 02:00 UTC, Jinjiang commented on docs/zh/api/README.md
> +- 类型: `Route`
```suggestion
- 类型：`Route`
```

2021-01-17 02:00 UTC, Jinjiang commented on docs/zh/api/README.md
> +  初始路由地址，表示路由开始的[路由信息对象](#路由对象)。可用在导航守卫以区分初始导航。
```suggestion
  以[路由对象](#路由对象)的格式展示初始路由地址，即路由开始的地方。可用在导航守卫中以区分初始导航。
```

2021-01-17 02:00 UTC, Jinjiang commented on docs/zh/api/README.md
> +*废弃*: 使用 [`route.addRoute()`](#router-addroute) 代替。
```suggestion
*已废弃*：使用 [`route.addRoute()`](#router-addroute) 代替。
```

2021-01-17 02:00 UTC, Jinjiang commented on docs/zh/api/README.md
> +获取所有激活的路由记录列表。**注意只有记录的属性才被视为公共 API**，避免使用任何其他属性，例如 `regex`，因为它在 Vue Router 4 中不存在。
```suggestion
获取所有活跃的路由记录列表。**注意只有文档中记录下来的 property 才被视为公共 API**，避免使用任何其它 property，例如 `regex`，因为它在 Vue Router 4 中不存在。
```

2021-01-24 01:56 UTC, Jinjiang approved these changes

2021-01-24 10:03 UTC, merged

2021-01-24 10:03 UTC, posva commented
Thank you both!