docs: Add type to the code of some md files
vuejs/vue-router pull request #3460
Opened 2021-01-27 03:08 UTC by FAKER-A

Add type to the code of some md files

2021-01-27 10:51 UTC, posva requested changes
Can you remove all the changes to `docs-gitbook`? those files should be removed

2021-01-27 11:06 UTC, FAKER-A commented
> Can you remove all the changes to `docs-gitbook`? those files should be removed

Ok Thanks Reply

2021-01-27 11:07 UTC, posva requested changes
The types were originally in flow, can you adapt them to TS by changing the `?{}` into `void` as well?

Thanks!

2021-01-27 11:07 UTC, posva commented on docs/api/README.md
>      { x: number, y: number } |
```suggestion
    { x?: number, y?: number } |
```

2021-01-28 01:59 UTC, FAKER-A commented on docs/api/README.md
>      { x: number, y: number } |
You mean this？
```ts
type PositionDescriptor =
    { x: number, y: number } |
    { selector: string } |
    void
```

2021-01-28 09:04 UTC, posva commented on docs/api/README.md
>      { x: number, y: number } |
yeah, that should do!

2021-01-28 09:36 UTC, FAKER-A commented on docs/api/README.md
>      { x: number, y: number } |
ok

2021-01-28 09:48 UTC, posva approved these changes
Thanks!

2021-01-28 09:48 UTC, merged