feat: add constructor hint
vuejs/vue-router pull request #3626
Opened 2021-09-05 10:05 UTC by Hazlank

Same with vue and vuex,add hint to tell user use new  `operator`

2021-09-05 12:45 UTC, posva requested changes
Thanks! Can you make the dev warn, dev only, capitalize router and move the instance of check to the first param of the warn?

2021-09-07 03:09 UTC, Hazlank commented
@posva ```warn``` include dev only, and i delete condition,it was only use 3 place,please check them

2021-10-01 14:59 UTC, posva requested changes

2021-10-01 14:59 UTC, posva commented on src/history/base.js
> +            console.error(err)
let's move the console.error outside of the if statement as it should be kept in production

2021-10-02 03:01 UTC, Hazlank commented
@posva my bad,I changed it :joy:

2021-10-03 09:03 UTC, posva approved these changes

2021-10-03 09:04 UTC, merged