fix: 🐛 treat isActive to case-insensitive
vuejs/vue-router pull request #3657
Opened 2021-10-28 12:46 UTC by Kyle-Ye

✅ Closes: #3656

2021-10-28 13:05 UTC, Kyle-Ye commented
Maybe we need to add some tests for this new behavior, any suggestion where to write the new test?

2021-10-28 15:26 UTC, posva requested changes
This is not the correct patch as there is an option to make the path matching case sensitive and this should respect it.
This information should be available on the route records as `regex.ignoreCase` or something similar.
Can you also add a few unit tests for isIncludeRoute?

2021-10-28 16:30 UTC, Kyle-Ye commented
> This is not the correct patch as there is an option to make the path matching case sensitive and this should respect it.
> This information should be available on the route records as `regex.ignoreCase` or something similar.
> Can you also add a few unit tests for isIncludeRoute?


Add the test and use regex.ignoreCase property. Any suggestion on how to safely get ignoreCase properly?

2021-10-29 03:03 UTC, Kyle-Ye commented on src/components/link.js
> +    const ignoreCase = current.matched[0].regex.ignoreCase
Any suggestion on how to safely get ignoreCase properly? @posva

2021-11-08 03:16 UTC, Kyle-Ye commented
Hello @posva. Any suggestion on this PR?

2023-07-07 17:49 UTC, closed without merging