Translate 2.0 docs for advanced & api (ja)
vuejs/vue-router pull request #691
Opened 2016-09-27 02:26 UTC by tejitak

Translate vue-router 2.0 docs for 'advanced' and 'api' in Japanese.

Note: All 2.0 doc Japanese translations were now completed with the PR https://github.com/vuejs/vue-router/pull/685

Reviewer: @kazupon

2016-09-27 02:35 UTC, kazupon commented
OK!
I'll try to review. :)

2016-09-27 08:28 UTC, kazupon requested changes
全般的に、`function` を `ファンクション` と訳していたのですが、これは、`関数` でいいと思います。

2016-09-27 08:28 UTC, kazupon commented on docs/ja/api/router-view.md
> +`<router-view>` コンポーネントは与えられたパスに対してマッチしたコンポーネントをレンダリングする funcitonal コンポーネントです。`<router-view>` の中でレンダリングされるコンポーネント自身もまた、ネストされたパスに対してコンポーネントをレンダリングするための `<router-view>` を持つことができます。
`functional コンポーネント` ですが、functional language の訳である、関数型言語を参考に、`関数型コンポーネント`にしましょう。
https://ja.wikipedia.org/wiki/関数型言語

実際、functional component は状態を持たないコンポーネントで、まさに関数型なので。

2016-09-28 02:40 UTC, tejitak commented
@kazupon Thanks! I updated it.

2016-09-28 03:52 UTC, kazupon approved these changes
👍

2016-09-28 03:53 UTC, kazupon commented
/ping @vuejs/vue-router 
Review done. Please merge this PR & #685  :)

2016-09-29 07:54 UTC, merged