Add event property to router-link
vuejs/vue-router pull request #786
Opened 2016-10-15 19:31 UTC by AdamNiederer

The event property allows the link to be activated on a custom event.
It defaults to click, so this shouldn't be a breaking change.

2016-10-16 04:53 UTC, yyx990803 commented
Wondering what's the use case for this?

2016-10-16 05:16 UTC, AdamNiederer commented
Binding `mousedown` instead of `click` to big navigation links makes your website feel a lot more responsive - that was the exigence for writing the patch. If your app can spend the 50ms between mousedown and mouseup loading components, that's a huge boost to felt responsiveness.

I'm sure there's a use for the other mouse events (wheel and doubleclick come to mind), and possibly the HTML5 drag events.

2016-10-16 07:10 UTC, fnlctrl commented
`mousedown` wouldn't work in mobile browsers, so some people may need to bind `touchstart` as well, then we may end up having to support binding multiple events...
I think we can just keep it simple by binding events explicitly on `<router-links>`.

2016-11-13 04:11 UTC, yyx990803 requested changes

2016-11-13 04:11 UTC, yyx990803 commented on src/components/link.js
> +      type: String,
I think it should also accept `Array` type, e.g. `<router-link :event="['mousedown', 'touchstart']"></router-link>`

2016-11-28 23:12 UTC, closed without merging