Support `target="_blank"` for `<router-link>`
vuejs/vue-router pull request #830
Opened 2016-10-25 08:28 UTC by fnlctrl

2016-10-25 08:44 UTC, phanan reviewed
I don't really know how to use this GitHub review. Should have made it a comment instead :P

2016-10-25 08:44 UTC, phanan commented on src/components/link.js
> +        if (target && target.value === '_blank') return
Two things:

* Why not `const target = this.$el && this.$el.getAttribute('target')`?
* Won't this fail for `target="_blank "` (with an extra space)?

2016-10-25 09:03 UTC, fnlctrl commented on src/components/link.js
> +        if (target && target.value === '_blank') return
Fixed, I guess I'm just too unfamiliar with native dom api :joy:

2016-10-27 10:38 UTC, hogart commented on src/components/link.js
> +        if (target && target.toLowerCase().split(' ').indexOf('_blank') > -1) return
Since code is written in ES Net, shouldn't it be `target.toLowerCase().split(' ').includes('_blank')`?

2016-10-27 11:18 UTC, fnlctrl commented on src/components/link.js
> +        if (target && target.toLowerCase().split(' ').indexOf('_blank') > -1) return
That cannot be transpiled, and would require a polyfill.

2016-11-07 12:03 UTC, posva approved these changes

2016-11-07 12:03 UTC, posva commented
@fnlctrl I absolutely forgot about this, sorry

2016-11-07 12:43 UTC, fnlctrl commented
@posva Totally forgot this too 😂😂😂
I think I'll just wait for Evan to get back to this.

2016-11-13 03:45 UTC, yyx990803 requested changes

2016-11-13 03:45 UTC, yyx990803 commented on src/components/link.js
> +        const target = this.$el && this.$el.getAttribute('target')
We should use `e.target` here. `this.$el` may be a wrapping `<li>` if `tag` prop is used.

2016-11-13 03:45 UTC, yyx990803 commented on src/components/link.js
> +        if (target && target.toLowerCase().split(' ').indexOf('_blank') > -1) return
how about just `/\b_blank\b/i.test(target)`

2016-11-13 19:34 UTC, merged

2017-06-20 04:20 UTC, nullest commented
@yyx990803 , hello you da, but how can i do it in the instance, like this:

`this.$router.push({name: 'users.index', target: '_blank'})`

2017-08-08 14:36 UTC, Mouvedia commented
If it's supported you should update [this line](https://github.com/vuejs/vuejs.org/commit/489145a05fc875660f1d5e0e57946629eeea8a8a#diff-2ff218682023cc310e3acd06a7271e63R270).