Router is able to recognize components by string
vuejs/vue-router pull request #899
Opened 2016-11-12 02:29 UTC by akoumjian

2016-11-12 17:36 UTC, fnlctrl commented
Thanks! Maybe `a component name that has been registered with Vue.component()` can be clearer?

2016-11-12 17:40 UTC, akoumjian commented
We could expand the example to use one of each possible entries and demonstrate by example. Also open to alternative language.

2016-11-13 04:13 UTC, yyx990803 requested changes

2016-11-13 04:13 UTC, yyx990803 commented on docs/en/essentials/getting-started.md
> +// Vue.extend(), a component name created with Vue.component(),
"a component id string registered via `Vue.component()`"

2016-11-14 19:18 UTC, merged